# Generated by Django 5.1.2 on 2025-11-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsageMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=128)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('labels', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['key'], name='analytics_u_key_1b21b9_idx')],
            },
        ),
    ]
