# Generated by Django 5.1.2 on 2025-11-13 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CelestialBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('body_type', models.CharField(choices=[('planet', 'Planet'), ('luminar', 'Luminar'), ('node', 'Node'), ('dwarf', 'Dwarf planet'), ('asteroid', 'Asteroid'), ('point', 'Calculated point')], default='planet', max_length=16)),
                ('symbol', models.CharField(blank=True, max_length=16)),
                ('is_retrograde_capable', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='NatalChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Natal Chart', max_length=128)),
                ('event_datetime', models.DateTimeField()),
                ('house_system', models.CharField(default='placidus', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('calculation_version', models.CharField(default='bioastro-2.0', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('event_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='natal_charts', to='core.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natal_charts', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='natal_charts', to='accounts.userprofile')),
            ],
            options={
                'ordering': ('-event_datetime',),
            },
        ),
        migrations.CreateModel(
            name='IntegralIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=32)),
                ('value', models.DecimalField(decimal_places=3, max_digits=6)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integral_indicators', to='charts.natalchart')),
            ],
            options={
                'ordering': ('chart', 'category', 'name'),
                'unique_together': {('chart', 'name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aspect_type', models.CharField(choices=[('conjunction', 'Conjunction'), ('opposition', 'Opposition'), ('trine', 'Trine'), ('square', 'Square'), ('sextile', 'Sextile'), ('quincunx', 'Quincunx'), ('semisextile', 'Semi-sextile'), ('semisquare', 'Semi-square'), ('quintile', 'Quintile'), ('biquintile', 'Bi-quintile')], max_length=32)),
                ('orb', models.DecimalField(decimal_places=2, max_digits=5)),
                ('intensity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('source_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspect_sources', to='charts.celestialbody')),
                ('target_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspect_targets', to='charts.celestialbody')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspects', to='charts.natalchart')),
            ],
            options={
                'ordering': ('chart', 'source_body__name'),
                'unique_together': {('chart', 'source_body', 'target_body', 'aspect_type')},
            },
        ),
        migrations.CreateModel(
            name='PlanetPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sign', models.CharField(max_length=16)),
                ('house', models.PositiveSmallIntegerField()),
                ('absolute_degree', models.DecimalField(decimal_places=3, max_digits=6)),
                ('retrograde', models.BooleanField(default=False)),
                ('speed', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='charts.celestialbody')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planet_positions', to='charts.natalchart')),
            ],
            options={
                'ordering': ('chart', 'body'),
                'unique_together': {('chart', 'body')},
            },
        ),
        migrations.CreateModel(
            name='PlanetStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_name', models.CharField(max_length=64)),
                ('score', models.DecimalField(decimal_places=3, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=3, default=1.0, max_digits=4)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strength_metrics', to='charts.celestialbody')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strength_metrics', to='charts.natalchart')),
            ],
            options={
                'ordering': ('chart', 'body', '-score'),
                'unique_together': {('chart', 'body', 'metric_name')},
            },
        ),
    ]
