# Generated by Django 5.1.2 on 2025-11-13 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('horizon', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('quarter', 'Quarter'), ('year', 'Year'), ('five_years', '5 Years'), ('ten_years', '10 Years'), ('thirty_years', '30 Years')], max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_batches', to='charts.natalchart')),
            ],
            options={
                'ordering': ('-start_date',),
                'unique_together': {('chart', 'horizon', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='ForecastEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('timeframe_start', models.DateTimeField()),
                ('timeframe_end', models.DateTimeField()),
                ('summary', models.TextField()),
                ('opportunities', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='forecasts.forecastbatch')),
            ],
            options={
                'ordering': ('timeframe_start',),
            },
        ),
    ]
